name: projectappsos
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  geolocator: ^13.0.1
  url_launcher: ^6.3.1
  permission_handler: ^11.3.0
  sensors_plus: ^5.0.1
  intl: ^0.20.2
  shimmer: ^3.0.0
  flutter_background_service: ^5.0.5
  flutter_background_service_android: ^6.2.2
  http: ^1.3.0
  cached_network_image: ^3.4.1
  flutter_local_notifications: ^17.0.0
  just_audio: ^0.9.36
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/sounds/

# เพิ่มการตั้งค่าเพื่อลดความเข้มงวดของ lints
analyzer:
  errors:
    untyped_exception: warning # ปรับให้ข้อผิดพลาดเกี่ยวกับ catch เป็น warning แทน error